/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ifal.cantina;

import com.ifal.cantina.controller.Controller;
import com.ifal.cantina.model.Model;
import com.ifal.cantina.view.View;

import java.io.FileInputStream;
import java.util.Properties;
import java.io.IOException;

/**
 * @author Nicolas Albuquerque R.
 */
public class App {

    private static String getPropertie(String keyPropertie) {
        Properties props = new Properties();
        String valuePropertie = null;
        try {
            props.load(new FileInputStream("application.properties"));
            valuePropertie = props.getProperty(keyPropertie);
        } catch (IOException error) {
            System.err.format("Erro ao ler o arquivo de propriedade: %s", error.getMessage());
        }

        return valuePropertie;
    }

    private static String getUrlConnection() {
        return String.format(
                "jdbc:%s://%s:%s/%s",
                getPropertie("db.type"),
                getPropertie("db.host"),
                getPropertie("db.port"),
                getPropertie("db.name"));
    }

    public static void main(String[] args) {
        Model model = new Model(getUrlConnection(), getPropertie("db.user"), getPropertie("db.password"));
        View view = new View();
        Controller controller = new Controller(model, view);

        controller.run();
    }
}
